// <auto-generated />
using System;
using GeeksDirectory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeeksDirectory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190921175653_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeeksDirectory.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b8eb90fa-e25a-43e1-a5b6-dadfc2bcf2a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5fade06-d6a6-4e23-bf56-ab678b5082c1",
                            Email = "sergey.zykov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SERGEY.ZYKOV@MAIL.SOME",
                            NormalizedUserName = "SERGEY.ZYKOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEACZ58zdtzy3DNmEujYTg6fSy0dpcqgopBzCAYvcRrN2Gz6/g+uJuNIA4m9VsAA/qw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1549963-5171-45ef-b96f-9ec05d7274a2",
                            TwoFactorEnabled = false,
                            UserName = "sergey.zykov@mail.some"
                        },
                        new
                        {
                            Id = "0a50dbc4-23b5-4e0d-b588-0a7a72df0ed1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4d69d7a-656e-472b-b057-1b37b69213bf",
                            Email = "john.smith@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.SMITH@MAIL.SOME",
                            NormalizedUserName = "JOHN.SMITH@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEB8W5NLTfuXUQB1lDiT4Z0mXjcMHmcGIJjqPDHZ0p8EeXaU6ULXIBne23O/b2la6Sw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "babf4b69-99d7-4f08-aa49-55772f6b09bf",
                            TwoFactorEnabled = false,
                            UserName = "john.smith@mail.some"
                        },
                        new
                        {
                            Id = "3fa5371e-5d44-42c6-b71f-daf3d38b2c5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26c036d9-5bbd-4b88-8c50-03b20e83db26",
                            Email = "ivan.ivanov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.IVANOV@MAIL.SOME",
                            NormalizedUserName = "IVAN.IVANOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEIeDS/oYm0kqJFQgOfTa/K6c160ARrzGRaUndDQuxB5uJMejZ3l6XqdcD5VGCHbKFg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "87f11ffc-4085-4e4a-8619-4af4a7e174c4",
                            TwoFactorEnabled = false,
                            UserName = "ivan.ivanov@mail.some"
                        },
                        new
                        {
                            Id = "8636b3d5-af78-4a6f-a773-c96404516ba5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46493b28-30cb-4132-a543-9f00d955d6a0",
                            Email = "dasha.egorova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DASHA.EGOROVA@MAIL.SOME",
                            NormalizedUserName = "DASHA.EGOROVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEJDDVIGa+gqnITTcXyn1zqkPOJTPC7WQzBN/je+wj1jN+FouRVzIULj4Y5KKyp7lFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "626f6f95-8cd1-4c0c-86ef-af84206e247e",
                            TwoFactorEnabled = false,
                            UserName = "dasha.egorova@mail.some"
                        },
                        new
                        {
                            Id = "4f99f9b1-b054-455e-9daa-8f0592823568",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e32412d-d2bb-4ceb-8bc1-8a76f91a92cc",
                            Email = "andrey.vladimirov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREY.VLADIMIROV@MAIL.SOME",
                            NormalizedUserName = "ANDREY.VLADIMIROV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBYMA9NO47YVZvN09QcGi7CE2dt3RQlnu0FWD8dFGL5ap9c7M8xQFSWXLygYd80xiw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8dcb4ec-ad54-4cb9-aa51-76798838d0fd",
                            TwoFactorEnabled = false,
                            UserName = "andrey.vladimirov@mail.some"
                        },
                        new
                        {
                            Id = "b270427f-fc46-4fdc-b3d9-3bdc64364d0e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76e868e0-3070-4f7b-863c-6ace2b63de6e",
                            Email = "violeta.kanygina@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VIOLETA.KANYGINA@MAIL.SOME",
                            NormalizedUserName = "VIOLETA.KANYGINA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEJkeKhsDi1L0cSDw4SISWm+GFHYz4zJBRTF6cK3jhLBw7AT0k+d73IkguUDAQiBPJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f62ea1bb-c72d-4f4c-be48-44d36a18855f",
                            TwoFactorEnabled = false,
                            UserName = "violeta.kanygina@mail.some"
                        },
                        new
                        {
                            Id = "dc440a63-da95-43b0-98aa-3f4c4ff2a053",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40a9fe4f-d5fe-477b-b6a9-3ac1eb196e76",
                            Email = "arsenia.panova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARSENIA.PANOVA@MAIL.SOME",
                            NormalizedUserName = "ARSENIA.PANOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEI5MeeiJ8LIcTMLacSpJ0S+wnShZRxiZOV0L3Jy6d44fwECX+gXDdlH76O/NG3xa5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0269c67-a128-4e61-b9be-efa029e49af3",
                            TwoFactorEnabled = false,
                            UserName = "arsenia.panova@mail.some"
                        },
                        new
                        {
                            Id = "964fb987-c3d0-4a17-a417-fb7edce1e3aa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "650a7ece-9aed-4e00-bc67-c7d05b548491",
                            Email = "radislav.barsov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RADISLAV.BARSOV@MAIL.SOME",
                            NormalizedUserName = "RADISLAV.BARSOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAmUAGUgqMzMPmnOzccZAYjrcxLwIB5iei/T882kkZ/W0MC1OtvNNXbVAmo0OKmb7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "972343c3-c73c-44f6-9787-89d3bd300aa9",
                            TwoFactorEnabled = false,
                            UserName = "radislav.barsov@mail.some"
                        },
                        new
                        {
                            Id = "46b27f3b-dca0-4b4a-8b2a-ab2b263c1171",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8552aa6-bb93-4ea5-96dc-7f8da23e215b",
                            Email = "vasya.alekseev@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VASYA.ALEKSEEV@MAIL.SOME",
                            NormalizedUserName = "VASYA.ALEKSEEV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBOYTe4erVX9GrhAJ+H5UZEBaMo8lPoNiHL7NDP+Cx/60RIwOPWgyK0mE6OnBMnD5g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e152985-cb5f-4128-ab8e-696e8cd91779",
                            TwoFactorEnabled = false,
                            UserName = "vasya.alekseev@mail.some"
                        },
                        new
                        {
                            Id = "1a206a7d-646f-4c48-8578-1d2e6a76df05",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "025bb42b-e330-46f2-9a5c-4d8e8dd4c210",
                            Email = "zlata.tretyakova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZLATA.TRETYAKOVA@MAIL.SOME",
                            NormalizedUserName = "ZLATA.TRETYAKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEENcvyX4vxLIuxlkPBCTRq9QGpNqVL2TeHZ2xnkc6/eG6BLCM9AHhmlxnarb9A/M7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "19c52718-bd2b-422b-935f-21710e6264ac",
                            TwoFactorEnabled = false,
                            UserName = "zlata.tretyakova@mail.some"
                        },
                        new
                        {
                            Id = "64642283-ef5f-4d48-9ef6-9a4e30b8332e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d385f8fb-8fa5-44d3-8277-252c0e46f73b",
                            Email = "albert.archipov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALBERT.ARCHIPOV@MAIL.SOME",
                            NormalizedUserName = "ALBERT.ARCHIPOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEEFGHu1QBKhXKP2ISGFT+gRlIjuJwR+BNdIbjEv35t9Vwfr6tQqyK3LoA18Baqqpbw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "412937f6-eafe-4c5c-83d2-0a5fee645f16",
                            TwoFactorEnabled = false,
                            UserName = "albert.archipov@mail.some"
                        },
                        new
                        {
                            Id = "bb88c60a-257e-4b84-9a07-45206ccb3aad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9bcada4e-20da-4afe-87a2-5ab33e816c76",
                            Email = "zarina.uvarova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZARINA.UVAROVA@MAIL.SOME",
                            NormalizedUserName = "ZARINA.UVAROVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBYyb2KDrGfH+mFP7Up51G4VRUK/ryD+MGVFsnSSwnLp+jJpOx+gGC12ULuwgFKxpg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aabc7d0b-e763-493e-8cf2-acfc47364674",
                            TwoFactorEnabled = false,
                            UserName = "zarina.uvarova@mail.some"
                        },
                        new
                        {
                            Id = "ab9f49d7-f20a-4951-88db-f75fcded0fe9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45bec219-eb76-46ae-970d-d7bc9c67d988",
                            Email = "nadezda.kolesnikova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NADEZDA.KOLESNIKOVA@MAIL.SOME",
                            NormalizedUserName = "NADEZDA.KOLESNIKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKKMguXL0CKMs6BdqfLOJ8Gh5tznQl3UPHFCyg975OCx3tGwId6Gn+AGIidEQ28jrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c27999ed-69c0-4e33-ac5d-233eb13a8b71",
                            TwoFactorEnabled = false,
                            UserName = "nadezda.kolesnikova@mail.some"
                        },
                        new
                        {
                            Id = "8bd9b467-e47b-4720-ad89-6eda8d254f86",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f5ef248-08da-4101-9c1c-00afee3a47a8",
                            Email = "alina.lazareva@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALINA.LAZAREVA@MAIL.SOME",
                            NormalizedUserName = "ALINA.LAZAREVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEHVo76x9Kdm3DiWajFSkVPa8Fi5B3x2xTIeFnz39vRMKI4qVUQppVpJXUGR7f49bbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc654304-e722-4cb0-a3f6-3d08a16b6464",
                            TwoFactorEnabled = false,
                            UserName = "alina.lazareva@mail.some"
                        },
                        new
                        {
                            Id = "a020921d-a94e-4606-b090-dc96d12ffd95",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f3b0ad1-dedc-4e15-82f4-e86000d29f1c",
                            Email = "galena.volkova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GALENA.VOLKOVA@MAIL.SOME",
                            NormalizedUserName = "GALENA.VOLKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEDRBf3QaS9yANGAxmaLAI+ErIp2hyJVL/S5oP2I3Ac1y8ODm1Ng13Wv/F7KOCElWyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "59d5525c-7221-41f2-a1ab-0ed307f12860",
                            TwoFactorEnabled = false,
                            UserName = "galena.volkova@mail.some"
                        },
                        new
                        {
                            Id = "83d419be-12fb-4c32-9079-44a6bf1f0086",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d5a1655-545e-4175-96bd-3a0a4a7d63d1",
                            Email = "vsevolod.lenin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VSEVOLOD.LENIN@MAIL.SOME",
                            NormalizedUserName = "VSEVOLOD.LENIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKDtp/FrJUqs2f2Dxck70Vqm5OKmjuqOJc3y06ipZ7/UyNAJJir1bnIYD54sXVZFPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e303ac1-149d-41e5-9409-e1378faf2fc8",
                            TwoFactorEnabled = false,
                            UserName = "vsevolod.lenin@mail.some"
                        },
                        new
                        {
                            Id = "dabe2f8b-5545-4572-8468-5febf3a15a09",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8af7891-1a58-4280-9d58-17035be05275",
                            Email = "oskar.kapustin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OSKAR.KAPUSTIN@MAIL.SOME",
                            NormalizedUserName = "OSKAR.KAPUSTIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEGbynSN33QSjtmC1HAkgQrhhQgR9Bjfi6v9b2ihU0cRVhYj0wLjhhzc+9UJnxAORNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e4bc32a-24f6-4815-b060-57bf0bd57c48",
                            TwoFactorEnabled = false,
                            UserName = "oskar.kapustin@mail.some"
                        },
                        new
                        {
                            Id = "4da310b4-87bb-4690-90c8-bf437114ae8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87d592bb-0cac-4269-ab64-622ce4b942cf",
                            Email = "vladimir.udin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADIMIR.UDIN@MAIL.SOME",
                            NormalizedUserName = "VLADIMIR.UDIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEME6oOkX5D5TWwU2GIS6DtHioxxSOfVCSapzf9ggxPaS530k2WOiPU+s3hM3OLtBKA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6bdd717-b554-4922-ab3b-c40a212fa2e9",
                            TwoFactorEnabled = false,
                            UserName = "vladimir.udin@mail.some"
                        },
                        new
                        {
                            Id = "73ad683c-7127-4b43-bc6c-c9e2a086d4c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04b8aa3b-56ce-487c-959f-0ab85aded04a",
                            Email = "lubov.orehova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LUBOV.OREHOVA@MAIL.SOME",
                            NormalizedUserName = "LUBOV.OREHOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKSH7de5k7h3eRvCgO288ZcDzurX35umCXYOsY/dj8ij/wUGUBHnYUqQ2UE4vbGtWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b23626d2-0cd6-4e09-b302-a501039832e7",
                            TwoFactorEnabled = false,
                            UserName = "lubov.orehova@mail.some"
                        },
                        new
                        {
                            Id = "ae8f195d-426c-45b3-8f56-17ef57fd3148",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab1b14f9-6ff7-4fd1-b383-2ea4916581d1",
                            Email = "vlada.lipnitskaya@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADA.LIPNITSKAYA@MAIL.SOME",
                            NormalizedUserName = "VLADA.LIPNITSKAYA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEIVnSwqZ0IfwBxiakrtLInzj43wz4RVeFqazG7xNNFmvntPmbF/wXwgTUro4oK8sTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5499590c-4c8a-4c9d-a649-183fcd91fb03",
                            TwoFactorEnabled = false,
                            UserName = "vlada.lipnitskaya@mail.some"
                        },
                        new
                        {
                            Id = "f61dd9a6-49ee-4c40-ae5a-9b6b9122a38e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c9e66302-43ed-449e-9b19-ed4dd0c006ae",
                            Email = "polina.davydova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "POLINA.DAVYDOVA@MAIL.SOME",
                            NormalizedUserName = "POLINA.DAVYDOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEDOFhwwbMvVkF4wwabUq4x8eYb5LKgNs7OxHpczdCjSMzo36pkfvIylCYj2op58oZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae6808f2-fc54-47cf-aa40-3fe98d6de68e",
                            TwoFactorEnabled = false,
                            UserName = "polina.davydova@mail.some"
                        },
                        new
                        {
                            Id = "d5a53242-1c53-42dd-8833-a5072b367d80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a6a817f3-8e61-4f3c-b6ec-b32d19e2e166",
                            Email = "vanera.ryabova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VANERA.RYABOVA@MAIL.SOME",
                            NormalizedUserName = "VANERA.RYABOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKUGxCOP+6KQEnRXJKAYqKS/W3Q9vrbl1Ud6xN1sKTxp6fujDaraDcrj3efwcfAAnQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2120090b-2156-4819-ae75-46ff15112b9f",
                            TwoFactorEnabled = false,
                            UserName = "vanera.ryabova@mail.some"
                        },
                        new
                        {
                            Id = "98d7661f-19ac-4909-bf20-e700dd07c19a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46f82492-77e4-48f8-a0f3-dff47f710893",
                            Email = "anjela.trofimova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANJELA.TROFIMOVA@MAIL.SOME",
                            NormalizedUserName = "ANJELA.TROFIMOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEE7KKxCc61yTzJwl+mKEZU91PQ7ARDMsxWBWwSiuFO15LtCuvd/u+Ujww0KOBfa4Aw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1669459-e6c8-4e4a-9b4f-2d52d0f81726",
                            TwoFactorEnabled = false,
                            UserName = "anjela.trofimova@mail.some"
                        },
                        new
                        {
                            Id = "511a47e8-9c86-4ce7-996f-9e1a72b53e69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c44fd2bf-521d-4eee-9bd9-f198369e6daf",
                            Email = "oskar.davtyan@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OSKAR.DAVTYAN@MAIL.SOME",
                            NormalizedUserName = "OSKAR.DAVTYAN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEE9d5H0bE1XCdMrKj/flcJsQdRoHldbGqi/L6tEk89hbNR7plRFfIizhvv4wvtcKrg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fa77d36b-5a36-468a-ae09-363bb3cf912d",
                            TwoFactorEnabled = false,
                            UserName = "oskar.davtyan@mail.some"
                        },
                        new
                        {
                            Id = "e30e2446-ad11-46d6-bc13-68097fae0440",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "deb7911f-7b9b-44b5-b465-d27ee1b80a19",
                            Email = "nikolay.borisov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKOLAY.BORISOV@MAIL.SOME",
                            NormalizedUserName = "NIKOLAY.BORISOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEC1r2/IcWMAuoyYumZppcza4PirmT0J9qumzSyfdHgakhpiosSidmS0EoUsJu4otIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "586a2159-6980-4512-ab54-59b6a0151c0e",
                            TwoFactorEnabled = false,
                            UserName = "nikolay.borisov@mail.some"
                        },
                        new
                        {
                            Id = "a728faec-b5c7-41f4-bd56-162a897ff46f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d54fa88-9f13-4535-8b47-1df7a8435a1f",
                            Email = "donat.latykin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DONAT.LATYKIN@MAIL.SOME",
                            NormalizedUserName = "DONAT.LATYKIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEEuHbC7Uz+89Bibowa0T6THKnZg98aLnaMLS3V/nZyWT6kfbrNLephgnHmRVkeFC+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f48bc8a-8c4d-4588-8152-0b338f1ef1ec",
                            TwoFactorEnabled = false,
                            UserName = "donat.latykin@mail.some"
                        },
                        new
                        {
                            Id = "b1091cd4-d605-480b-aa23-6f49df0e53ad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "323240ad-419b-4059-9638-5f9864b2b4c3",
                            Email = "maksim.kuzmin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAKSIM.KUZMIN@MAIL.SOME",
                            NormalizedUserName = "MAKSIM.KUZMIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEMvC4RyWUeumNvk4mRB+kjoKGE2vR8+uDeHfqk/K/X1QNXold+pZ0o334K2U+NYArg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d5764f9-e21f-466e-b0e5-eeea5db5df80",
                            TwoFactorEnabled = false,
                            UserName = "maksim.kuzmin@mail.some"
                        });
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score");

                    b.Property<int>("SkillId");

                    b.Property<string>("UserName");

                    b.HasKey("AssessmentId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserName");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.GeekProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.Property<string>("UserName");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserName");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            City = "Moscow",
                            Name = "Sergey",
                            Surname = "Zykov",
                            UserName = "b8eb90fa-e25a-43e1-a5b6-dadfc2bcf2a1"
                        },
                        new
                        {
                            ProfileId = 2,
                            City = "Ekaterinburg",
                            Name = "John",
                            Surname = "Smith",
                            UserName = "0a50dbc4-23b5-4e0d-b588-0a7a72df0ed1"
                        },
                        new
                        {
                            ProfileId = 3,
                            City = "St. Petersburg",
                            Name = "Ivan",
                            Surname = "Ivanov",
                            UserName = "3fa5371e-5d44-42c6-b71f-daf3d38b2c5b"
                        },
                        new
                        {
                            ProfileId = 4,
                            City = "Deport",
                            Name = "Dasha",
                            Surname = "Egorova",
                            UserName = "8636b3d5-af78-4a6f-a773-c96404516ba5"
                        },
                        new
                        {
                            ProfileId = 5,
                            City = "Landmark",
                            Name = "Andrey",
                            Surname = "Vladimirov",
                            UserName = "4f99f9b1-b054-455e-9daa-8f0592823568"
                        },
                        new
                        {
                            ProfileId = 6,
                            City = "New Preston",
                            Name = "Violeta",
                            Surname = "Kanygina",
                            UserName = "b270427f-fc46-4fdc-b3d9-3bdc64364d0e"
                        },
                        new
                        {
                            ProfileId = 7,
                            City = "Dupree",
                            Name = "Arsenia",
                            Surname = "Panova",
                            UserName = "dc440a63-da95-43b0-98aa-3f4c4ff2a053"
                        },
                        new
                        {
                            ProfileId = 8,
                            City = "Kenton Vale",
                            Name = "Radislav",
                            Surname = "Barsov",
                            UserName = "964fb987-c3d0-4a17-a417-fb7edce1e3aa"
                        },
                        new
                        {
                            ProfileId = 9,
                            City = "Walnut Park",
                            Name = "Vasya",
                            Surname = "Alekseev",
                            UserName = "46b27f3b-dca0-4b4a-8b2a-ab2b263c1171"
                        },
                        new
                        {
                            ProfileId = 10,
                            City = "Karaichev",
                            Name = "Zlata",
                            Surname = "Tretyakova",
                            UserName = "1a206a7d-646f-4c48-8578-1d2e6a76df05"
                        },
                        new
                        {
                            ProfileId = 11,
                            City = "Golitsyno",
                            Name = "Albert",
                            Surname = "Archipov",
                            UserName = "64642283-ef5f-4d48-9ef6-9a4e30b8332e"
                        },
                        new
                        {
                            ProfileId = 12,
                            City = "Trostyanka",
                            Name = "Zarina",
                            Surname = "Uvarova",
                            UserName = "bb88c60a-257e-4b84-9a07-45206ccb3aad"
                        },
                        new
                        {
                            ProfileId = 13,
                            City = "Stawropol",
                            Name = "Nadezda",
                            Surname = "Kolesnikova",
                            UserName = "ab9f49d7-f20a-4951-88db-f75fcded0fe9"
                        },
                        new
                        {
                            ProfileId = 14,
                            City = "Lykoshina",
                            Name = "Alina",
                            Surname = "Lazareva",
                            UserName = "8bd9b467-e47b-4720-ad89-6eda8d254f86"
                        },
                        new
                        {
                            ProfileId = 15,
                            City = "Agutino",
                            Name = "Galena",
                            Surname = "Volkova",
                            UserName = "a020921d-a94e-4606-b090-dc96d12ffd95"
                        },
                        new
                        {
                            ProfileId = 16,
                            City = "Ungavitsa",
                            Name = "Vsevolod",
                            Surname = "Lenin",
                            UserName = "83d419be-12fb-4c32-9079-44a6bf1f0086"
                        },
                        new
                        {
                            ProfileId = 17,
                            City = "Shvedovo",
                            Name = "Oskar",
                            Surname = "Kapustin",
                            UserName = "dabe2f8b-5545-4572-8468-5febf3a15a09"
                        },
                        new
                        {
                            ProfileId = 18,
                            City = "Skolkovo",
                            Name = "Vladimir",
                            Surname = "Udin",
                            UserName = "4da310b4-87bb-4690-90c8-bf437114ae8e"
                        },
                        new
                        {
                            ProfileId = 19,
                            City = "Ragozina",
                            Name = "Lubov",
                            Surname = "Orehova",
                            UserName = "73ad683c-7127-4b43-bc6c-c9e2a086d4c1"
                        },
                        new
                        {
                            ProfileId = 20,
                            City = "Nikitino",
                            Name = "Vlada",
                            Surname = "Lipnitskaya",
                            UserName = "ae8f195d-426c-45b3-8f56-17ef57fd3148"
                        },
                        new
                        {
                            ProfileId = 21,
                            City = "Aryntsas",
                            Name = "Polina",
                            Surname = "Davydova",
                            UserName = "f61dd9a6-49ee-4c40-ae5a-9b6b9122a38e"
                        },
                        new
                        {
                            ProfileId = 22,
                            City = "Krutilovka",
                            Name = "Vanera",
                            Surname = "Ryabova",
                            UserName = "d5a53242-1c53-42dd-8833-a5072b367d80"
                        },
                        new
                        {
                            ProfileId = 23,
                            City = "Khvatkovo",
                            Name = "Anjela",
                            Surname = "Trofimova",
                            UserName = "98d7661f-19ac-4909-bf20-e700dd07c19a"
                        },
                        new
                        {
                            ProfileId = 24,
                            City = "Latoshinka",
                            Name = "Oskar",
                            Surname = "Davtyan",
                            UserName = "511a47e8-9c86-4ce7-996f-9e1a72b53e69"
                        },
                        new
                        {
                            ProfileId = 25,
                            City = "Mikhaylovka",
                            Name = "Nikolay",
                            Surname = "Borisov",
                            UserName = "e30e2446-ad11-46d6-bc13-68097fae0440"
                        },
                        new
                        {
                            ProfileId = 26,
                            City = "Nygda",
                            Name = "Donat",
                            Surname = "Latykin",
                            UserName = "a728faec-b5c7-41f4-bd56-162a897ff46f"
                        },
                        new
                        {
                            ProfileId = 27,
                            City = "Taygach",
                            Name = "Maksim",
                            Surname = "Kuzmin",
                            UserName = "b1091cd4-d605-480b-aa23-6f49df0e53ad"
                        });
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AverageScore");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProfileId");

                    b.HasKey("SkillId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 1
                        },
                        new
                        {
                            SkillId = 2,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 3,
                            AverageScore = 2,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 4,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 5,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 6,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 3
                        },
                        new
                        {
                            SkillId = 7,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 4
                        },
                        new
                        {
                            SkillId = 8,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 4
                        },
                        new
                        {
                            SkillId = 9,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 10,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 6
                        },
                        new
                        {
                            SkillId = 11,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 7
                        },
                        new
                        {
                            SkillId = 12,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 13,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 14,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 15,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 16,
                            AverageScore = 1,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 17,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 18,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 19,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 10
                        },
                        new
                        {
                            SkillId = 20,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 21,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 22,
                            AverageScore = 3,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 23,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 24,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 25,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 26,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 27,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 28,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 29,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 30,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 31,
                            AverageScore = 2,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 32,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 33,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 34,
                            AverageScore = 1,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 35,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 36,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 37,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 38,
                            AverageScore = 1,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 39,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 40,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 41,
                            AverageScore = 1,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 42,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 43,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 18
                        },
                        new
                        {
                            SkillId = 44,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "javascript",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 45,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 46,
                            AverageScore = 2,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 47,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 48,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 49,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 50,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 51,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 52,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 53,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 54,
                            AverageScore = 1,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 55,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 56,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 57,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 58,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 59,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 60,
                            AverageScore = 1,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 61,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 62,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 63,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 64,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 65,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 66,
                            AverageScore = 1,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 67,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 68,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 69,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 70,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 71,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 72,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 24
                        },
                        new
                        {
                            SkillId = 73,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 25
                        },
                        new
                        {
                            SkillId = 74,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 25
                        },
                        new
                        {
                            SkillId = 75,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 26
                        },
                        new
                        {
                            SkillId = 76,
                            AverageScore = 3,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 26
                        },
                        new
                        {
                            SkillId = 77,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 27
                        },
                        new
                        {
                            SkillId = 78,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 27
                        },
                        new
                        {
                            SkillId = 79,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 27
                        },
                        new
                        {
                            SkillId = 80,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 27
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Assessment", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.Skill", "Skill")
                        .WithMany("Assessments")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.GeekProfile", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Skill", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.GeekProfile", "Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
