// <auto-generated />
using System;
using GeeksDirectory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeeksDirectory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190928143640_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GeeksDirectory.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b8eb90fa-e25a-43e1-a5b6-dadfc2bcf2a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5df37ac7-4b40-4967-a2cb-27c869ba22d6",
                            Email = "sergey.zykov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SERGEY.ZYKOV@MAIL.SOME",
                            NormalizedUserName = "SERGEY.ZYKOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEMSsZ2C2hYBOP5isrytuaPTeqnFj7fLLjk92IFnDAvJgXuKEGKdtBmwNLayRz0lFlg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18cfc0df-7747-44be-b5e2-713bfdd38099",
                            TwoFactorEnabled = false,
                            UserName = "sergey.zykov@mail.some"
                        },
                        new
                        {
                            Id = "0a50dbc4-23b5-4e0d-b588-0a7a72df0ed1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96fd0033-8708-4df0-b1d8-5ab89c3eaddd",
                            Email = "john.smith@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.SMITH@MAIL.SOME",
                            NormalizedUserName = "JOHN.SMITH@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEDDvA64xMBs1Hw22egpzT57yLkfbzC6o6kajIQYN+jDBERcLlUojqCMrK7kM87JeCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55ca4ab1-0f12-4264-b7d7-b675d6dfc8e1",
                            TwoFactorEnabled = false,
                            UserName = "john.smith@mail.some"
                        },
                        new
                        {
                            Id = "3fa5371e-5d44-42c6-b71f-daf3d38b2c5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85f5e17e-940c-4f88-a0e8-e3895647fbf1",
                            Email = "ivan.ivanov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.IVANOV@MAIL.SOME",
                            NormalizedUserName = "IVAN.IVANOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKLdbZVMJRUbhSXT1U//U/qo6NP280acR2WQSQHGvBB4rRgEQ+fg4eBhRCQ4Ma3ruA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f2374fbd-2bb1-4ab8-890d-1daf5b4ddcc3",
                            TwoFactorEnabled = false,
                            UserName = "ivan.ivanov@mail.some"
                        },
                        new
                        {
                            Id = "8636b3d5-af78-4a6f-a773-c96404516ba5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a79be290-3ddd-4540-a0ee-72477a4fdd3a",
                            Email = "dasha.egorova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DASHA.EGOROVA@MAIL.SOME",
                            NormalizedUserName = "DASHA.EGOROVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBZKr6YBS7ApTKh2EoCH2DYRP5kdHFq57wvgjXx26AEE5F3A6CW0EAN9DmexS207vQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8999ab89-9ee8-4e51-a860-96c8bea14ebc",
                            TwoFactorEnabled = false,
                            UserName = "dasha.egorova@mail.some"
                        },
                        new
                        {
                            Id = "4f99f9b1-b054-455e-9daa-8f0592823568",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f971ea07-bcf1-4a3f-bbbc-81aec5d4fa10",
                            Email = "andrey.vladimirov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREY.VLADIMIROV@MAIL.SOME",
                            NormalizedUserName = "ANDREY.VLADIMIROV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEG3QMVo0YMprdh7Rldva71rhn6axrhqnY9wKtOx4gyO4UIFs5vA2I1ZoI+GhEtxLNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb49e97e-ea36-4917-9b73-aefa978a81a1",
                            TwoFactorEnabled = false,
                            UserName = "andrey.vladimirov@mail.some"
                        },
                        new
                        {
                            Id = "b270427f-fc46-4fdc-b3d9-3bdc64364d0e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9d9cbc66-4597-4790-808b-dbc4cc9bd746",
                            Email = "violeta.kanygina@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VIOLETA.KANYGINA@MAIL.SOME",
                            NormalizedUserName = "VIOLETA.KANYGINA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEPn4AMLGNKcA3p1+4tuOTYbrlhVC46DnbwwUHQmXyJhHzjz5foyYlZhQwbuRbrKO0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d755a677-ae36-45ff-9792-324e6f5e68c4",
                            TwoFactorEnabled = false,
                            UserName = "violeta.kanygina@mail.some"
                        },
                        new
                        {
                            Id = "dc440a63-da95-43b0-98aa-3f4c4ff2a053",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "84c43ae6-7c9b-49ad-9b3f-2126928a02fe",
                            Email = "arsenia.panova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARSENIA.PANOVA@MAIL.SOME",
                            NormalizedUserName = "ARSENIA.PANOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEDLWgogfxA6i5xZuRxZOd1fH6bXf2ql5yQjSwmUR40QO4OcKzYH6/5bh26Wurfv4mA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b907564-2e3a-4a4e-b4a9-f16a1c92fbf7",
                            TwoFactorEnabled = false,
                            UserName = "arsenia.panova@mail.some"
                        },
                        new
                        {
                            Id = "964fb987-c3d0-4a17-a417-fb7edce1e3aa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d354a8e-41e3-4ad2-ba11-bb9062b05f7e",
                            Email = "radislav.barsov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RADISLAV.BARSOV@MAIL.SOME",
                            NormalizedUserName = "RADISLAV.BARSOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAELzvMmPk7U55Tho4Xu0860HhNdQpEPXilyG7iGlW+dCZh9RA5DEr0XApd9bLi8M0Tg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b10fcbb-3ec6-4a99-9ef7-da2725cee2ed",
                            TwoFactorEnabled = false,
                            UserName = "radislav.barsov@mail.some"
                        },
                        new
                        {
                            Id = "46b27f3b-dca0-4b4a-8b2a-ab2b263c1171",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "570a1b8e-cb5b-4039-96e4-83f3eba3f28c",
                            Email = "vasya.alekseev@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VASYA.ALEKSEEV@MAIL.SOME",
                            NormalizedUserName = "VASYA.ALEKSEEV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBn6RxtwEIf3+XlfN1Ud+/Im3vay4WAjiQckyheMxnSmo/hb1cB8bMPZj7RFRl65cQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ea7efdd-6220-44f6-8752-f468dc60a398",
                            TwoFactorEnabled = false,
                            UserName = "vasya.alekseev@mail.some"
                        },
                        new
                        {
                            Id = "1a206a7d-646f-4c48-8578-1d2e6a76df05",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ec81a69c-bc0c-472e-b2aa-93083c4d3715",
                            Email = "zlata.tretyakova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZLATA.TRETYAKOVA@MAIL.SOME",
                            NormalizedUserName = "ZLATA.TRETYAKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKDrfg8+hT7bmTxqBGHGrtOJ+uH2vlkcAxjdo3oT/BLb76wSNJyzY0AXI1Od7Hzqhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fbebfdfe-50e7-4e93-adfa-bb007b22321d",
                            TwoFactorEnabled = false,
                            UserName = "zlata.tretyakova@mail.some"
                        },
                        new
                        {
                            Id = "64642283-ef5f-4d48-9ef6-9a4e30b8332e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c517a0de-f239-4c5c-84a2-a0c563a6175a",
                            Email = "albert.archipov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALBERT.ARCHIPOV@MAIL.SOME",
                            NormalizedUserName = "ALBERT.ARCHIPOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAELd4x72kyniyzoIbWTgNN+tHvem3qXQNBmxRJJsAh7/zboQ+EV3e3XVXkNp2K6wZLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9d1aa6e-d7e6-46e3-85a4-17a625a5297f",
                            TwoFactorEnabled = false,
                            UserName = "albert.archipov@mail.some"
                        },
                        new
                        {
                            Id = "bb88c60a-257e-4b84-9a07-45206ccb3aad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8db6cf46-3d6e-4136-94c1-061c1c58e7b7",
                            Email = "zarina.uvarova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZARINA.UVAROVA@MAIL.SOME",
                            NormalizedUserName = "ZARINA.UVAROVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAENxJ4s6cNNtxtbn8vuv2K1Y9HC1gfUWZue/WU3yNU8pb4gp/vdPl3a1PS7IpJQcF7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "667d0c87-aad5-4fae-85a3-e6fca48841d4",
                            TwoFactorEnabled = false,
                            UserName = "zarina.uvarova@mail.some"
                        },
                        new
                        {
                            Id = "ab9f49d7-f20a-4951-88db-f75fcded0fe9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b15ce872-57a0-4b98-8428-569fa6967130",
                            Email = "nadezda.kolesnikova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NADEZDA.KOLESNIKOVA@MAIL.SOME",
                            NormalizedUserName = "NADEZDA.KOLESNIKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEIT4/Ov6Ahl7WRZ343XR0hHIlYAjF7msrEX+fnd72TZI+k5E9uBHZMnHBQKkOUwVDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6aa05ce0-9f6a-4b74-b2d6-b98b4f8fc0f1",
                            TwoFactorEnabled = false,
                            UserName = "nadezda.kolesnikova@mail.some"
                        },
                        new
                        {
                            Id = "8bd9b467-e47b-4720-ad89-6eda8d254f86",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "963a6ab1-a8ef-4ea1-8215-cc270943f43e",
                            Email = "alina.lazareva@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALINA.LAZAREVA@MAIL.SOME",
                            NormalizedUserName = "ALINA.LAZAREVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAECBkQMMqOR0wPN+6Ev1Z1/eQSUafRso7Orfr4bcRScurxKn3NsM+xmmP5M42EAUR6g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dbfb6f2a-98d2-4f66-a94f-c10bac1c1eb2",
                            TwoFactorEnabled = false,
                            UserName = "alina.lazareva@mail.some"
                        },
                        new
                        {
                            Id = "a020921d-a94e-4606-b090-dc96d12ffd95",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa048c49-de33-467f-ba1e-c2c40302c09d",
                            Email = "galena.volkova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GALENA.VOLKOVA@MAIL.SOME",
                            NormalizedUserName = "GALENA.VOLKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKfKt3dk1Xb0iUj2PGX1KNWZHHhIou0wezUNDMupkH6XQhAi5Ns+DHTqHQw++AFgPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "729771ec-987c-486e-b927-8c45fe2831e1",
                            TwoFactorEnabled = false,
                            UserName = "galena.volkova@mail.some"
                        },
                        new
                        {
                            Id = "83d419be-12fb-4c32-9079-44a6bf1f0086",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0457752-e93b-4983-a3c4-21d2dd2bb94c",
                            Email = "vsevolod.lenin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VSEVOLOD.LENIN@MAIL.SOME",
                            NormalizedUserName = "VSEVOLOD.LENIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKt3HAZvdb7eX1zPX2T2iAoN653xpKz2ovCqwgSnBSUirOMpd4dxSnbkeoSfW2hbeA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f0d69115-570f-4b9a-85fd-f25fe33561c3",
                            TwoFactorEnabled = false,
                            UserName = "vsevolod.lenin@mail.some"
                        },
                        new
                        {
                            Id = "dabe2f8b-5545-4572-8468-5febf3a15a09",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d26f014d-0720-4032-9e2b-71df0273b530",
                            Email = "oskar.kapustin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OSKAR.KAPUSTIN@MAIL.SOME",
                            NormalizedUserName = "OSKAR.KAPUSTIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEFHnik+8fIgUDCG7rSVNKfxYxqu+KfifbP9h2TrHE0bC/qDH+S8Y3oGAGQNVCNrtdQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9fee0f22-7888-41e1-b597-c80af67a821a",
                            TwoFactorEnabled = false,
                            UserName = "oskar.kapustin@mail.some"
                        },
                        new
                        {
                            Id = "4da310b4-87bb-4690-90c8-bf437114ae8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e898006f-10ac-422b-b702-67d4d741a550",
                            Email = "vladimir.udin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADIMIR.UDIN@MAIL.SOME",
                            NormalizedUserName = "VLADIMIR.UDIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEMlF07EFJ0iIRcg+wD7cKvyyHFqnpZoGBntuzTgIIpCTFSOoMsheq/yg8emrU1KCNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "933153df-7fc9-4a34-b985-395b23b0318e",
                            TwoFactorEnabled = false,
                            UserName = "vladimir.udin@mail.some"
                        },
                        new
                        {
                            Id = "73ad683c-7127-4b43-bc6c-c9e2a086d4c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59409089-39a1-4321-8b9d-c54563f5a40e",
                            Email = "lubov.orehova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LUBOV.OREHOVA@MAIL.SOME",
                            NormalizedUserName = "LUBOV.OREHOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAECsJF1YQiwzBffaBqOls0Pf0mH/eaz2OtgGp0H+geC+Cvw+tYyl4artgQNIXcjYBzQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ad1e001-2c25-46fa-b784-df9aa97844d4",
                            TwoFactorEnabled = false,
                            UserName = "lubov.orehova@mail.some"
                        },
                        new
                        {
                            Id = "ae8f195d-426c-45b3-8f56-17ef57fd3148",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6b97dbf-fce1-48eb-a3ff-ab8a43ff93f4",
                            Email = "vlada.lipnitskaya@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADA.LIPNITSKAYA@MAIL.SOME",
                            NormalizedUserName = "VLADA.LIPNITSKAYA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ8OqqgJPrKHVNh3e+Onyl2wmuBuUwhjo/bPZQRkBtUiAUajBGogCoCHtsGq8xKnKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1ba207c8-9bdd-4d86-b61c-0a1903c25712",
                            TwoFactorEnabled = false,
                            UserName = "vlada.lipnitskaya@mail.some"
                        },
                        new
                        {
                            Id = "f61dd9a6-49ee-4c40-ae5a-9b6b9122a38e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6f5c2856-cf44-44a1-9aa1-c8598bcbab91",
                            Email = "polina.davydova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "POLINA.DAVYDOVA@MAIL.SOME",
                            NormalizedUserName = "POLINA.DAVYDOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEB8dZIglVQ/r7nKycoVlvItqtWnXp5VP2Yrk3cwZepU4vmFbT+/WnuTjUJAvWuKbig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65a084a6-8e5f-4562-9591-685a052812d0",
                            TwoFactorEnabled = false,
                            UserName = "polina.davydova@mail.some"
                        },
                        new
                        {
                            Id = "d5a53242-1c53-42dd-8833-a5072b367d80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3570372b-86f4-4073-9883-a5c59a6d01bb",
                            Email = "vanera.ryabova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VANERA.RYABOVA@MAIL.SOME",
                            NormalizedUserName = "VANERA.RYABOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKv1GBUnUFw/6tFjUDnLQUmwXATSJa+J/NQY5S74QhIZx1Vx940dcUAdyuYrHgL5+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b544274-daef-477f-a15e-eb52b1a524e1",
                            TwoFactorEnabled = false,
                            UserName = "vanera.ryabova@mail.some"
                        },
                        new
                        {
                            Id = "98d7661f-19ac-4909-bf20-e700dd07c19a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edc63674-6c41-4d0e-a526-1a525efd99d2",
                            Email = "anjela.trofimova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANJELA.TROFIMOVA@MAIL.SOME",
                            NormalizedUserName = "ANJELA.TROFIMOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAECJAVQ0VBngMGUcq9XA96m4OrIp3zhmO73k4yYkkjSdTGkdfRsu5KiNBLTaAF88YXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3a5a69c9-6f81-4408-ac46-2b99ab1f500f",
                            TwoFactorEnabled = false,
                            UserName = "anjela.trofimova@mail.some"
                        },
                        new
                        {
                            Id = "511a47e8-9c86-4ce7-996f-9e1a72b53e69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d175b7e1-a206-42de-a361-57350ff748ee",
                            Email = "oskar.davtyan@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OSKAR.DAVTYAN@MAIL.SOME",
                            NormalizedUserName = "OSKAR.DAVTYAN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEPYW+iAHjP/4SSJBKAnShcBNwji+drpGv23EzChV7Py5kiMBMs7s0ALaYbOKqh7o5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5dc366c7-859b-45f9-a6d6-7c2144c5fb7f",
                            TwoFactorEnabled = false,
                            UserName = "oskar.davtyan@mail.some"
                        },
                        new
                        {
                            Id = "e30e2446-ad11-46d6-bc13-68097fae0440",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce392859-b7ae-4405-8815-064549924cec",
                            Email = "nikolay.borisov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKOLAY.BORISOV@MAIL.SOME",
                            NormalizedUserName = "NIKOLAY.BORISOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEH03GOydHwouiqsHTowPvoXCyBHdoIRnuxb5iRFjYakk8gYw9UHMgU+BomNnHrh9HQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77456845-64eb-4d17-b212-b01bb778aa16",
                            TwoFactorEnabled = false,
                            UserName = "nikolay.borisov@mail.some"
                        },
                        new
                        {
                            Id = "a728faec-b5c7-41f4-bd56-162a897ff46f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ded61cf9-6f60-47fc-ba20-4e28248cd095",
                            Email = "donat.latykin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DONAT.LATYKIN@MAIL.SOME",
                            NormalizedUserName = "DONAT.LATYKIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEHSwdpF7LMOSB74dXbY/+x48tjjip5NHmI1q01LaDVZHW5ZWrjUCSJylwhq9m3crfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3f6ad75-0522-4e53-8acf-2c007dff3789",
                            TwoFactorEnabled = false,
                            UserName = "donat.latykin@mail.some"
                        },
                        new
                        {
                            Id = "b1091cd4-d605-480b-aa23-6f49df0e53ad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9d7b5a2-9056-42e8-b96a-abec19b4b71a",
                            Email = "maksim.kuzmin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAKSIM.KUZMIN@MAIL.SOME",
                            NormalizedUserName = "MAKSIM.KUZMIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEH4Ph2KZ4tMcx68wDLOlBRDlsXKMGDD06QK3Om4W/oZrDmcqXpQ1yfb/EisHv/DPRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4a9cf6b-47e4-48c3-bd73-dd4e50346bd6",
                            TwoFactorEnabled = false,
                            UserName = "maksim.kuzmin@mail.some"
                        });
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Score");

                    b.Property<int>("SkillId");

                    b.Property<string>("UserName");

                    b.HasKey("AssessmentId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserName");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.GeekProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.Property<string>("UserName");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserName");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            City = "Moscow",
                            Name = "Sergey",
                            Surname = "Zykov",
                            UserName = "b8eb90fa-e25a-43e1-a5b6-dadfc2bcf2a1"
                        },
                        new
                        {
                            ProfileId = 2,
                            City = "Ekaterinburg",
                            Name = "John",
                            Surname = "Smith",
                            UserName = "0a50dbc4-23b5-4e0d-b588-0a7a72df0ed1"
                        },
                        new
                        {
                            ProfileId = 3,
                            City = "St. Petersburg",
                            Name = "Ivan",
                            Surname = "Ivanov",
                            UserName = "3fa5371e-5d44-42c6-b71f-daf3d38b2c5b"
                        },
                        new
                        {
                            ProfileId = 4,
                            City = "Deport",
                            Name = "Dasha",
                            Surname = "Egorova",
                            UserName = "8636b3d5-af78-4a6f-a773-c96404516ba5"
                        },
                        new
                        {
                            ProfileId = 5,
                            City = "Landmark",
                            Name = "Andrey",
                            Surname = "Vladimirov",
                            UserName = "4f99f9b1-b054-455e-9daa-8f0592823568"
                        },
                        new
                        {
                            ProfileId = 6,
                            City = "New Preston",
                            Name = "Violeta",
                            Surname = "Kanygina",
                            UserName = "b270427f-fc46-4fdc-b3d9-3bdc64364d0e"
                        },
                        new
                        {
                            ProfileId = 7,
                            City = "Dupree",
                            Name = "Arsenia",
                            Surname = "Panova",
                            UserName = "dc440a63-da95-43b0-98aa-3f4c4ff2a053"
                        },
                        new
                        {
                            ProfileId = 8,
                            City = "Kenton Vale",
                            Name = "Radislav",
                            Surname = "Barsov",
                            UserName = "964fb987-c3d0-4a17-a417-fb7edce1e3aa"
                        },
                        new
                        {
                            ProfileId = 9,
                            City = "Walnut Park",
                            Name = "Vasya",
                            Surname = "Alekseev",
                            UserName = "46b27f3b-dca0-4b4a-8b2a-ab2b263c1171"
                        },
                        new
                        {
                            ProfileId = 10,
                            City = "Karaichev",
                            Name = "Zlata",
                            Surname = "Tretyakova",
                            UserName = "1a206a7d-646f-4c48-8578-1d2e6a76df05"
                        },
                        new
                        {
                            ProfileId = 11,
                            City = "Golitsyno",
                            Name = "Albert",
                            Surname = "Archipov",
                            UserName = "64642283-ef5f-4d48-9ef6-9a4e30b8332e"
                        },
                        new
                        {
                            ProfileId = 12,
                            City = "Trostyanka",
                            Name = "Zarina",
                            Surname = "Uvarova",
                            UserName = "bb88c60a-257e-4b84-9a07-45206ccb3aad"
                        },
                        new
                        {
                            ProfileId = 13,
                            City = "Stawropol",
                            Name = "Nadezda",
                            Surname = "Kolesnikova",
                            UserName = "ab9f49d7-f20a-4951-88db-f75fcded0fe9"
                        },
                        new
                        {
                            ProfileId = 14,
                            City = "Lykoshina",
                            Name = "Alina",
                            Surname = "Lazareva",
                            UserName = "8bd9b467-e47b-4720-ad89-6eda8d254f86"
                        },
                        new
                        {
                            ProfileId = 15,
                            City = "Agutino",
                            Name = "Galena",
                            Surname = "Volkova",
                            UserName = "a020921d-a94e-4606-b090-dc96d12ffd95"
                        },
                        new
                        {
                            ProfileId = 16,
                            City = "Ungavitsa",
                            Name = "Vsevolod",
                            Surname = "Lenin",
                            UserName = "83d419be-12fb-4c32-9079-44a6bf1f0086"
                        },
                        new
                        {
                            ProfileId = 17,
                            City = "Shvedovo",
                            Name = "Oskar",
                            Surname = "Kapustin",
                            UserName = "dabe2f8b-5545-4572-8468-5febf3a15a09"
                        },
                        new
                        {
                            ProfileId = 18,
                            City = "Skolkovo",
                            Name = "Vladimir",
                            Surname = "Udin",
                            UserName = "4da310b4-87bb-4690-90c8-bf437114ae8e"
                        },
                        new
                        {
                            ProfileId = 19,
                            City = "Ragozina",
                            Name = "Lubov",
                            Surname = "Orehova",
                            UserName = "73ad683c-7127-4b43-bc6c-c9e2a086d4c1"
                        },
                        new
                        {
                            ProfileId = 20,
                            City = "Nikitino",
                            Name = "Vlada",
                            Surname = "Lipnitskaya",
                            UserName = "ae8f195d-426c-45b3-8f56-17ef57fd3148"
                        },
                        new
                        {
                            ProfileId = 21,
                            City = "Aryntsas",
                            Name = "Polina",
                            Surname = "Davydova",
                            UserName = "f61dd9a6-49ee-4c40-ae5a-9b6b9122a38e"
                        },
                        new
                        {
                            ProfileId = 22,
                            City = "Krutilovka",
                            Name = "Vanera",
                            Surname = "Ryabova",
                            UserName = "d5a53242-1c53-42dd-8833-a5072b367d80"
                        },
                        new
                        {
                            ProfileId = 23,
                            City = "Khvatkovo",
                            Name = "Anjela",
                            Surname = "Trofimova",
                            UserName = "98d7661f-19ac-4909-bf20-e700dd07c19a"
                        },
                        new
                        {
                            ProfileId = 24,
                            City = "Latoshinka",
                            Name = "Oskar",
                            Surname = "Davtyan",
                            UserName = "511a47e8-9c86-4ce7-996f-9e1a72b53e69"
                        },
                        new
                        {
                            ProfileId = 25,
                            City = "Mikhaylovka",
                            Name = "Nikolay",
                            Surname = "Borisov",
                            UserName = "e30e2446-ad11-46d6-bc13-68097fae0440"
                        },
                        new
                        {
                            ProfileId = 26,
                            City = "Nygda",
                            Name = "Donat",
                            Surname = "Latykin",
                            UserName = "a728faec-b5c7-41f4-bd56-162a897ff46f"
                        },
                        new
                        {
                            ProfileId = 27,
                            City = "Taygach",
                            Name = "Maksim",
                            Surname = "Kuzmin",
                            UserName = "b1091cd4-d605-480b-aa23-6f49df0e53ad"
                        });
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AverageScore");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProfileId");

                    b.HasKey("SkillId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            AverageScore = 1,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 1
                        },
                        new
                        {
                            SkillId = 2,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 1
                        },
                        new
                        {
                            SkillId = 3,
                            AverageScore = 1,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 4,
                            AverageScore = 2,
                            Description = "Ut enim ad minima, exercitationem ullam.",
                            Name = "java",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 5,
                            AverageScore = 3,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 6,
                            AverageScore = 4,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 7,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 8,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 9,
                            AverageScore = 3,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 3
                        },
                        new
                        {
                            SkillId = 10,
                            AverageScore = 2,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 4
                        },
                        new
                        {
                            SkillId = 11,
                            AverageScore = 1,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 4
                        },
                        new
                        {
                            SkillId = 12,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 4
                        },
                        new
                        {
                            SkillId = 13,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 14,
                            AverageScore = 3,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 6
                        },
                        new
                        {
                            SkillId = 15,
                            AverageScore = 0,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 7
                        },
                        new
                        {
                            SkillId = 16,
                            AverageScore = 3,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 7
                        },
                        new
                        {
                            SkillId = 17,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 7
                        },
                        new
                        {
                            SkillId = 18,
                            AverageScore = 2,
                            Description = "Quis autem eum iur velit esse quam.",
                            Name = "javascript",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 19,
                            AverageScore = 1,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 20,
                            AverageScore = 1,
                            Description = "Ut enim ad minima, exercitationem ullam.",
                            Name = "java",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 21,
                            AverageScore = 3,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 22,
                            AverageScore = 0,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 23,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 24,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 25,
                            AverageScore = 4,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 26,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 27,
                            AverageScore = 0,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 10
                        },
                        new
                        {
                            SkillId = 28,
                            AverageScore = 0,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 29,
                            AverageScore = 4,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 30,
                            AverageScore = 4,
                            Description = "Ut enim ad minima, exercitationem ullam.",
                            Name = "java",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 31,
                            AverageScore = 1,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 32,
                            AverageScore = 3,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 33,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 34,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 35,
                            AverageScore = 1,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 36,
                            AverageScore = 1,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 37,
                            AverageScore = 3,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 38,
                            AverageScore = 1,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 39,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 40,
                            AverageScore = 2,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 41,
                            AverageScore = 0,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 42,
                            AverageScore = 4,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 43,
                            AverageScore = 1,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 44,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 45,
                            AverageScore = 2,
                            Description = "Lorem ipsum dolor sit amet.",
                            Name = "csharp",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 46,
                            AverageScore = 2,
                            Description = "Quis autem eum iur velit esse quam.",
                            Name = "javascript",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 47,
                            AverageScore = 0,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 48,
                            AverageScore = 4,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 49,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 50,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 18
                        },
                        new
                        {
                            SkillId = 51,
                            AverageScore = 2,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 18
                        },
                        new
                        {
                            SkillId = 52,
                            AverageScore = 1,
                            Description = "Ut enim ad minima, exercitationem ullam.",
                            Name = "java",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 53,
                            AverageScore = 1,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 54,
                            AverageScore = 4,
                            Description = "Ut enim ad minima, exercitationem ullam.",
                            Name = "java",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 55,
                            AverageScore = 0,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 56,
                            AverageScore = 0,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 57,
                            AverageScore = 1,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 58,
                            AverageScore = 4,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 59,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 60,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 61,
                            AverageScore = 4,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 62,
                            AverageScore = 2,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 63,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 64,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voptatem aut odit.",
                            Name = "swift",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 65,
                            AverageScore = 0,
                            Description = "Excepteur sint cupitat, anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 66,
                            AverageScore = 3,
                            Description = "Excepteur sint in culpa id est laborum.",
                            Name = "python",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 67,
                            AverageScore = 1,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 68,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 69,
                            AverageScore = 2,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 24
                        },
                        new
                        {
                            SkillId = 70,
                            AverageScore = 3,
                            Description = "Quis autem eum iur velit esse quam.",
                            Name = "javascript",
                            ProfileId = 25
                        },
                        new
                        {
                            SkillId = 71,
                            AverageScore = 4,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 25
                        },
                        new
                        {
                            SkillId = 72,
                            AverageScore = 3,
                            Description = "Excepteur occaecat cupida proident, suntid est.",
                            Name = "cpp",
                            ProfileId = 26
                        },
                        new
                        {
                            SkillId = 73,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure repreherit in ea quam.",
                            Name = "php",
                            ProfileId = 26
                        },
                        new
                        {
                            SkillId = 74,
                            AverageScore = 4,
                            Description = "Lorem ipsum dolor sit amet.",
                            Name = "csharp",
                            ProfileId = 27
                        },
                        new
                        {
                            SkillId = 75,
                            AverageScore = 0,
                            Description = "Quis autem eum iur velit esse quam.",
                            Name = "javascript",
                            ProfileId = 27
                        },
                        new
                        {
                            SkillId = 76,
                            AverageScore = 3,
                            Description = "Nemo enim sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 27
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Assessment", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.Skill", "Skill")
                        .WithMany("Assessments")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.GeekProfile", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Skill", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.GeekProfile", "Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
