// <auto-generated />
using System;
using GeeksDirectory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeeksDirectory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GeeksDirectory.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b8eb90fa-e25a-43e1-a5b6-dadfc2bcf2a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc15ffea-704e-4bc2-819c-2f6e93120692",
                            Email = "sergey.zykov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SERGEY.ZYKOV@MAIL.SOME",
                            NormalizedUserName = "SERGEY.ZYKOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAELnOrTUIse1FYOicgj9azB8fg2VDZC6sHgEsUOQvfcPfn0GyruNOsJ5rVNiCLeoh3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1b4a91bc-d37d-4e13-ac8c-5f0c6fdf5c09",
                            TwoFactorEnabled = false,
                            UserName = "sergey.zykov@mail.some"
                        },
                        new
                        {
                            Id = "0a50dbc4-23b5-4e0d-b588-0a7a72df0ed1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0a539c7-527f-4f8d-98c6-efeae6b7d032",
                            Email = "john.smith@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.SMITH@MAIL.SOME",
                            NormalizedUserName = "JOHN.SMITH@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEPaTyUGwJTpb4cEDcA+7NqoK8WpH+GN/zux41wPII1KHilSch7vC8XMwC8NlynRiRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ca8d982-623f-4849-86cb-7333d85f1d00",
                            TwoFactorEnabled = false,
                            UserName = "john.smith@mail.some"
                        },
                        new
                        {
                            Id = "3fa5371e-5d44-42c6-b71f-daf3d38b2c5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee1e1cc3-dbad-4e37-b9ee-6dccccf27261",
                            Email = "ivan.ivanov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.IVANOV@MAIL.SOME",
                            NormalizedUserName = "IVAN.IVANOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEIHEvcfSLH0zdDuszArTNQJHtyppVo6cHMKvqI04fI6XVeX14Nd0uFQPNQ7NYNnIKA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c0ca75e-a580-42dc-bd79-df1ab42a65df",
                            TwoFactorEnabled = false,
                            UserName = "ivan.ivanov@mail.some"
                        },
                        new
                        {
                            Id = "8636b3d5-af78-4a6f-a773-c96404516ba5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7622e3a-18a1-4fff-bd2f-be680b6c31fd",
                            Email = "dasha.egorova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DASHA.EGOROVA@MAIL.SOME",
                            NormalizedUserName = "DASHA.EGOROVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEItpQRm863ANEykLHEpbu95ev8nAenp0siB9lLe2d0NSGCkMaNidQlLK3Qklxiplvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e4f40cdb-ecd8-4ba5-9e38-25e21a0a6b8b",
                            TwoFactorEnabled = false,
                            UserName = "dasha.egorova@mail.some"
                        },
                        new
                        {
                            Id = "4f99f9b1-b054-455e-9daa-8f0592823568",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10f0b96f-5fdf-4d63-b2ee-a70a287dc2e8",
                            Email = "andrey.vladimirov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREY.VLADIMIROV@MAIL.SOME",
                            NormalizedUserName = "ANDREY.VLADIMIROV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEEWU+YcEGEoLe1Tgm0+NxODpCURprYfg7Zz6dQXSJ8oTsPNPBekyJ/kb9fvM2l3fSg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef994637-f106-428b-88d1-4f9c62099aa5",
                            TwoFactorEnabled = false,
                            UserName = "andrey.vladimirov@mail.some"
                        },
                        new
                        {
                            Id = "b270427f-fc46-4fdc-b3d9-3bdc64364d0e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b70f2a2a-2f91-4196-977c-ed21a236584f",
                            Email = "violeta.kanygina@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VIOLETA.KANYGINA@MAIL.SOME",
                            NormalizedUserName = "VIOLETA.KANYGINA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEKQwDa1b1bKCVkGjKWUL+iEDv8GlLQEhgCouqtahbsCoeNLY012xP8xq60kQyxSzIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31777f87-2c18-4e47-a92b-3fd1bcdacb8c",
                            TwoFactorEnabled = false,
                            UserName = "violeta.kanygina@mail.some"
                        },
                        new
                        {
                            Id = "dc440a63-da95-43b0-98aa-3f4c4ff2a053",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db7fbb08-0811-4410-b0e7-2ec3a15b01b2",
                            Email = "arsenia.panova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARSENIA.PANOVA@MAIL.SOME",
                            NormalizedUserName = "ARSENIA.PANOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEGIn+YM7oDLtXs2o70VFdkAf/wTT2IdjmyVrh45pu8Hf/3gQbvjRJaq5cIZ93DhcEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cd19d407-2a73-46bf-b9da-b073f454ab24",
                            TwoFactorEnabled = false,
                            UserName = "arsenia.panova@mail.some"
                        },
                        new
                        {
                            Id = "964fb987-c3d0-4a17-a417-fb7edce1e3aa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43a101c5-cd8a-4a47-b812-9a089e718fe0",
                            Email = "radislav.barsov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RADISLAV.BARSOV@MAIL.SOME",
                            NormalizedUserName = "RADISLAV.BARSOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEDX+X+WWTIPCQL3xPz5quNX/CDAv3Mp9/LmWz0T4aGPiAEWqW/Y47GOXgw6BmBcjJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "87a94efa-40a7-46a9-9106-94644e1c671c",
                            TwoFactorEnabled = false,
                            UserName = "radislav.barsov@mail.some"
                        },
                        new
                        {
                            Id = "46b27f3b-dca0-4b4a-8b2a-ab2b263c1171",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f96c6f33-24b0-4062-b6ba-db60eb060be0",
                            Email = "vasya.alekseev@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VASYA.ALEKSEEV@MAIL.SOME",
                            NormalizedUserName = "VASYA.ALEKSEEV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBmqcOYwgTABUKy/ZeZPuMW/+vciTQ++B9oa9MjMwoTs6efdQ1SRBxyrFVkFcbXGVw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0502cd2c-8d0d-44bc-8cc3-d58182ffb2c8",
                            TwoFactorEnabled = false,
                            UserName = "vasya.alekseev@mail.some"
                        },
                        new
                        {
                            Id = "1a206a7d-646f-4c48-8578-1d2e6a76df05",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "440d0332-8636-4684-8f00-2f55599f34f9",
                            Email = "zlata.tretyakova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZLATA.TRETYAKOVA@MAIL.SOME",
                            NormalizedUserName = "ZLATA.TRETYAKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEMD23lnzjb085g7riaLIFprUYicqXbLm672mLTAgV1X+AQRC75b1q3Ct6cgS3CURzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e0a9110e-cb58-4d0d-b35a-400b61502078",
                            TwoFactorEnabled = false,
                            UserName = "zlata.tretyakova@mail.some"
                        },
                        new
                        {
                            Id = "64642283-ef5f-4d48-9ef6-9a4e30b8332e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "19dd5afe-ddd0-44e6-8b4d-bb70af0f704f",
                            Email = "albert.archipov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALBERT.ARCHIPOV@MAIL.SOME",
                            NormalizedUserName = "ALBERT.ARCHIPOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEHW3X5gXKVnKPbVjv2q/VZd2SoJPURi2uk7kHkfvQTNtFQhCSCv7AI+ZeAJaNcqvRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9b87232-7fa0-4ce3-9b2c-f058aa806dd1",
                            TwoFactorEnabled = false,
                            UserName = "albert.archipov@mail.some"
                        },
                        new
                        {
                            Id = "bb88c60a-257e-4b84-9a07-45206ccb3aad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d2691e8f-7c54-468b-b668-07c2c735d884",
                            Email = "zarina.uvarova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZARINA.UVAROVA@MAIL.SOME",
                            NormalizedUserName = "ZARINA.UVAROVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAeAJCZeM5Loh5v9Cz6Oa//SFqnyAWBZS9vy3q7nCtddGoDUF6KUSrbQaVvpGFKJ6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "39c2307e-6d85-4c56-b22b-a02e3fe39c7b",
                            TwoFactorEnabled = false,
                            UserName = "zarina.uvarova@mail.some"
                        },
                        new
                        {
                            Id = "ab9f49d7-f20a-4951-88db-f75fcded0fe9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2fb8f0b-c65a-4b84-b668-709ec22bc4ab",
                            Email = "nadezda.kolesnikova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NADEZDA.KOLESNIKOVA@MAIL.SOME",
                            NormalizedUserName = "NADEZDA.KOLESNIKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAbXDlibpRLwMXmDBtnKyfp06YHzfDfQGMxQ0kmRdGrK5CnKT97tVIcc5qtAOyTQ4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc13897e-3e65-4a9c-be1a-876648911881",
                            TwoFactorEnabled = false,
                            UserName = "nadezda.kolesnikova@mail.some"
                        },
                        new
                        {
                            Id = "8bd9b467-e47b-4720-ad89-6eda8d254f86",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34bc4695-81e4-4789-8a54-b8a80e1dab7e",
                            Email = "alina.lazareva@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALINA.LAZAREVA@MAIL.SOME",
                            NormalizedUserName = "ALINA.LAZAREVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEN2VyIbIlj3wmFvRtetoa28ti8cX9YeugNiRVPq8KN4t87HC27sLAco/61gVilTAcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f994d7f-5c26-404e-8f10-b108dc74f596",
                            TwoFactorEnabled = false,
                            UserName = "alina.lazareva@mail.some"
                        },
                        new
                        {
                            Id = "a020921d-a94e-4606-b090-dc96d12ffd95",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8f01a99-0354-453f-9a7a-76aacea3cb94",
                            Email = "galena.volkova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GALENA.VOLKOVA@MAIL.SOME",
                            NormalizedUserName = "GALENA.VOLKOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYC2LQrv3E7D5grrHji8QQEWrlzFTQznBxJV53kvk7PuG7Eg8glspD5qmN71d4bdQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "311aecf3-4991-4fb2-a4bb-a2fc58053b70",
                            TwoFactorEnabled = false,
                            UserName = "galena.volkova@mail.some"
                        },
                        new
                        {
                            Id = "83d419be-12fb-4c32-9079-44a6bf1f0086",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c65cdce-cd49-4a1a-b640-c118fb9ba254",
                            Email = "vsevolod.lenin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VSEVOLOD.LENIN@MAIL.SOME",
                            NormalizedUserName = "VSEVOLOD.LENIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEOYMHwMNYgG1ta4JRJmgUgV+dTfVrIwl5Jw4FozDYxjqwLgDnGKOg6XuwLP8kyArHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd080270-1fd1-4e86-a238-5e733c7fd84c",
                            TwoFactorEnabled = false,
                            UserName = "vsevolod.lenin@mail.some"
                        },
                        new
                        {
                            Id = "dabe2f8b-5545-4572-8468-5febf3a15a09",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca7649a1-abfa-49d6-9497-ccb65126ff08",
                            Email = "oskar.kapustin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OSKAR.KAPUSTIN@MAIL.SOME",
                            NormalizedUserName = "OSKAR.KAPUSTIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEFFA8MQ0CSB2wDszzKR/I4zVdxTynLLMzecy08nwHN052WhGA5RIS6p05z5U06L2wQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a58cf444-e330-4688-ad6c-7ee0d65c8c5c",
                            TwoFactorEnabled = false,
                            UserName = "oskar.kapustin@mail.some"
                        },
                        new
                        {
                            Id = "4da310b4-87bb-4690-90c8-bf437114ae8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8b127f2c-927f-483c-a2ec-b4d150469119",
                            Email = "vladimir.udin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADIMIR.UDIN@MAIL.SOME",
                            NormalizedUserName = "VLADIMIR.UDIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEJyd8oDdSpASS/H1G0Rb/8ASwgwBxcv18W0NjqN33lrqI8l59DR0b/2OaR8dsUq3LA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3df0db9-6a98-4764-ae51-52e16bb689a2",
                            TwoFactorEnabled = false,
                            UserName = "vladimir.udin@mail.some"
                        },
                        new
                        {
                            Id = "73ad683c-7127-4b43-bc6c-c9e2a086d4c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66aa020e-6331-48d1-a1f7-aedd25727351",
                            Email = "lubov.orehova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LUBOV.OREHOVA@MAIL.SOME",
                            NormalizedUserName = "LUBOV.OREHOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAlQh+fItP6SKi5Thupcbeb9oAuEtWJutnEU2ci409cdpVGaTxoILTtxSINWuKdnSA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9443557-ec3a-4b1f-92a4-68d49b3a4866",
                            TwoFactorEnabled = false,
                            UserName = "lubov.orehova@mail.some"
                        },
                        new
                        {
                            Id = "ae8f195d-426c-45b3-8f56-17ef57fd3148",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "661d4bd5-7037-4d0e-a086-067d7f801124",
                            Email = "vlada.lipnitskaya@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VLADA.LIPNITSKAYA@MAIL.SOME",
                            NormalizedUserName = "VLADA.LIPNITSKAYA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEMy0GIub0l20LxYrUdKgoScDUE7nEGdg2lUx/H9kk7MNGYUMrV/1PcsofYZbZQwDWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1b2ba1c7-5a23-47e9-89b3-bad7e6a55bdf",
                            TwoFactorEnabled = false,
                            UserName = "vlada.lipnitskaya@mail.some"
                        },
                        new
                        {
                            Id = "f61dd9a6-49ee-4c40-ae5a-9b6b9122a38e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bcb65171-303a-4150-920a-f4a11f85e96a",
                            Email = "polina.davydova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "POLINA.DAVYDOVA@MAIL.SOME",
                            NormalizedUserName = "POLINA.DAVYDOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBzEUUkSFj+w11JeJLgqrf6lYhPL/d9o3Q8bJytWZVqNl9Cpi8KW3C5TgWmSbcRtMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0cbc34f9-aa34-45dd-93c9-4b93b74e518f",
                            TwoFactorEnabled = false,
                            UserName = "polina.davydova@mail.some"
                        },
                        new
                        {
                            Id = "d5a53242-1c53-42dd-8833-a5072b367d80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3dce8241-72c8-4988-9b6c-12ae676b14d6",
                            Email = "vanera.ryabova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VANERA.RYABOVA@MAIL.SOME",
                            NormalizedUserName = "VANERA.RYABOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEHGhgCA7uWZm9kwM/4fbuDLOHxM7Rpua82UxOL/EaXlpJtyGf3HzXr4V2C7JqQRDwg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4bf171da-04cf-4a0b-b8a7-04f45c25ac7b",
                            TwoFactorEnabled = false,
                            UserName = "vanera.ryabova@mail.some"
                        },
                        new
                        {
                            Id = "98d7661f-19ac-4909-bf20-e700dd07c19a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0227bc5-d988-4704-8acc-4e0e6b5a12a7",
                            Email = "anjela.trofimova@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANJELA.TROFIMOVA@MAIL.SOME",
                            NormalizedUserName = "ANJELA.TROFIMOVA@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEOYvNOlT/A59Rk0xsnpxBaGnjQpt2jywdlaqz2Glv5kU0yjSIvC/lRbmOXSt7jGy2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5caee5fc-5399-498f-af7e-f552fea95346",
                            TwoFactorEnabled = false,
                            UserName = "anjela.trofimova@mail.some"
                        },
                        new
                        {
                            Id = "511a47e8-9c86-4ce7-996f-9e1a72b53e69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "398a8551-2b8f-4fd3-a995-558f5309cf59",
                            Email = "oskar.davtyan@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OSKAR.DAVTYAN@MAIL.SOME",
                            NormalizedUserName = "OSKAR.DAVTYAN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEB8+k+25cR+EYulU3XHHlHzBGoJIujQX6JAtM6CVehzhpJYZ7oJ1TfsXcTJSkwqJaA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e7f44f4-2dd4-4733-bdba-cf8b453d9103",
                            TwoFactorEnabled = false,
                            UserName = "oskar.davtyan@mail.some"
                        },
                        new
                        {
                            Id = "e30e2446-ad11-46d6-bc13-68097fae0440",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2ad7ee5-d009-4ce5-9063-2c5db6be54a5",
                            Email = "nikolay.borisov@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKOLAY.BORISOV@MAIL.SOME",
                            NormalizedUserName = "NIKOLAY.BORISOV@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBVd8wQPfP3oHSsgko/g8QGPBbWt6fUOHM4PPjrVPcLM+FSs1ivjGhoXalodgid+Yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7cc18e88-7271-4a15-8a19-dc1c29063476",
                            TwoFactorEnabled = false,
                            UserName = "nikolay.borisov@mail.some"
                        },
                        new
                        {
                            Id = "a728faec-b5c7-41f4-bd56-162a897ff46f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78c03f2b-c279-4da3-99cc-47d44e410017",
                            Email = "donat.latykin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DONAT.LATYKIN@MAIL.SOME",
                            NormalizedUserName = "DONAT.LATYKIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEMOz6Lp8ZgawwxjzztJW1G21FybGJ6B0WJeCRUlJIgWlJ3n/BhM/vgkm3lHmSTgYcw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "820e23ca-d33c-4b96-8726-f4af9f5fbe8f",
                            TwoFactorEnabled = false,
                            UserName = "donat.latykin@mail.some"
                        },
                        new
                        {
                            Id = "b1091cd4-d605-480b-aa23-6f49df0e53ad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca7dc424-9c14-4531-9dcf-cb5f30a32347",
                            Email = "maksim.kuzmin@mail.some",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAKSIM.KUZMIN@MAIL.SOME",
                            NormalizedUserName = "MAKSIM.KUZMIN@MAIL.SOME",
                            PasswordHash = "AQAAAAEAACcQAAAAEJkICa9UgjMnF4WvO9xBNdWakgACNqs0eSQDgqw3TQQTYdSMHA/fD/C1tS9c1VAlFg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74a93651-399d-4676-aaef-3c35853e0681",
                            TwoFactorEnabled = false,
                            UserName = "maksim.kuzmin@mail.some"
                        });
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Score");

                    b.Property<int>("SkillId");

                    b.Property<string>("UserName");

                    b.HasKey("AssessmentId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserName");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.GeekProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.Property<string>("UserName");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserName");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            City = "Moscow",
                            Name = "Sergey",
                            Surname = "Zykov",
                            UserName = "b8eb90fa-e25a-43e1-a5b6-dadfc2bcf2a1"
                        },
                        new
                        {
                            ProfileId = 2,
                            City = "Ekaterinburg",
                            Name = "John",
                            Surname = "Smith",
                            UserName = "0a50dbc4-23b5-4e0d-b588-0a7a72df0ed1"
                        },
                        new
                        {
                            ProfileId = 3,
                            City = "St. Petersburg",
                            Name = "Ivan",
                            Surname = "Ivanov",
                            UserName = "3fa5371e-5d44-42c6-b71f-daf3d38b2c5b"
                        },
                        new
                        {
                            ProfileId = 4,
                            City = "Deport",
                            Name = "Dasha",
                            Surname = "Egorova",
                            UserName = "8636b3d5-af78-4a6f-a773-c96404516ba5"
                        },
                        new
                        {
                            ProfileId = 5,
                            City = "Landmark",
                            Name = "Andrey",
                            Surname = "Vladimirov",
                            UserName = "4f99f9b1-b054-455e-9daa-8f0592823568"
                        },
                        new
                        {
                            ProfileId = 6,
                            City = "New Preston",
                            Name = "Violeta",
                            Surname = "Kanygina",
                            UserName = "b270427f-fc46-4fdc-b3d9-3bdc64364d0e"
                        },
                        new
                        {
                            ProfileId = 7,
                            City = "Dupree",
                            Name = "Arsenia",
                            Surname = "Panova",
                            UserName = "dc440a63-da95-43b0-98aa-3f4c4ff2a053"
                        },
                        new
                        {
                            ProfileId = 8,
                            City = "Kenton Vale",
                            Name = "Radislav",
                            Surname = "Barsov",
                            UserName = "964fb987-c3d0-4a17-a417-fb7edce1e3aa"
                        },
                        new
                        {
                            ProfileId = 9,
                            City = "Walnut Park",
                            Name = "Vasya",
                            Surname = "Alekseev",
                            UserName = "46b27f3b-dca0-4b4a-8b2a-ab2b263c1171"
                        },
                        new
                        {
                            ProfileId = 10,
                            City = "Karaichev",
                            Name = "Zlata",
                            Surname = "Tretyakova",
                            UserName = "1a206a7d-646f-4c48-8578-1d2e6a76df05"
                        },
                        new
                        {
                            ProfileId = 11,
                            City = "Golitsyno",
                            Name = "Albert",
                            Surname = "Archipov",
                            UserName = "64642283-ef5f-4d48-9ef6-9a4e30b8332e"
                        },
                        new
                        {
                            ProfileId = 12,
                            City = "Trostyanka",
                            Name = "Zarina",
                            Surname = "Uvarova",
                            UserName = "bb88c60a-257e-4b84-9a07-45206ccb3aad"
                        },
                        new
                        {
                            ProfileId = 13,
                            City = "Stawropol",
                            Name = "Nadezda",
                            Surname = "Kolesnikova",
                            UserName = "ab9f49d7-f20a-4951-88db-f75fcded0fe9"
                        },
                        new
                        {
                            ProfileId = 14,
                            City = "Lykoshina",
                            Name = "Alina",
                            Surname = "Lazareva",
                            UserName = "8bd9b467-e47b-4720-ad89-6eda8d254f86"
                        },
                        new
                        {
                            ProfileId = 15,
                            City = "Agutino",
                            Name = "Galena",
                            Surname = "Volkova",
                            UserName = "a020921d-a94e-4606-b090-dc96d12ffd95"
                        },
                        new
                        {
                            ProfileId = 16,
                            City = "Ungavitsa",
                            Name = "Vsevolod",
                            Surname = "Lenin",
                            UserName = "83d419be-12fb-4c32-9079-44a6bf1f0086"
                        },
                        new
                        {
                            ProfileId = 17,
                            City = "Shvedovo",
                            Name = "Oskar",
                            Surname = "Kapustin",
                            UserName = "dabe2f8b-5545-4572-8468-5febf3a15a09"
                        },
                        new
                        {
                            ProfileId = 18,
                            City = "Skolkovo",
                            Name = "Vladimir",
                            Surname = "Udin",
                            UserName = "4da310b4-87bb-4690-90c8-bf437114ae8e"
                        },
                        new
                        {
                            ProfileId = 19,
                            City = "Ragozina",
                            Name = "Lubov",
                            Surname = "Orehova",
                            UserName = "73ad683c-7127-4b43-bc6c-c9e2a086d4c1"
                        },
                        new
                        {
                            ProfileId = 20,
                            City = "Nikitino",
                            Name = "Vlada",
                            Surname = "Lipnitskaya",
                            UserName = "ae8f195d-426c-45b3-8f56-17ef57fd3148"
                        },
                        new
                        {
                            ProfileId = 21,
                            City = "Aryntsas",
                            Name = "Polina",
                            Surname = "Davydova",
                            UserName = "f61dd9a6-49ee-4c40-ae5a-9b6b9122a38e"
                        },
                        new
                        {
                            ProfileId = 22,
                            City = "Krutilovka",
                            Name = "Vanera",
                            Surname = "Ryabova",
                            UserName = "d5a53242-1c53-42dd-8833-a5072b367d80"
                        },
                        new
                        {
                            ProfileId = 23,
                            City = "Khvatkovo",
                            Name = "Anjela",
                            Surname = "Trofimova",
                            UserName = "98d7661f-19ac-4909-bf20-e700dd07c19a"
                        },
                        new
                        {
                            ProfileId = 24,
                            City = "Latoshinka",
                            Name = "Oskar",
                            Surname = "Davtyan",
                            UserName = "511a47e8-9c86-4ce7-996f-9e1a72b53e69"
                        },
                        new
                        {
                            ProfileId = 25,
                            City = "Mikhaylovka",
                            Name = "Nikolay",
                            Surname = "Borisov",
                            UserName = "e30e2446-ad11-46d6-bc13-68097fae0440"
                        },
                        new
                        {
                            ProfileId = 26,
                            City = "Nygda",
                            Name = "Donat",
                            Surname = "Latykin",
                            UserName = "a728faec-b5c7-41f4-bd56-162a897ff46f"
                        },
                        new
                        {
                            ProfileId = 27,
                            City = "Taygach",
                            Name = "Maksim",
                            Surname = "Kuzmin",
                            UserName = "b1091cd4-d605-480b-aa23-6f49df0e53ad"
                        });
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AverageScore");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProfileId");

                    b.HasKey("SkillId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 1
                        },
                        new
                        {
                            SkillId = 2,
                            AverageScore = 1,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 1
                        },
                        new
                        {
                            SkillId = 3,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 1
                        },
                        new
                        {
                            SkillId = 4,
                            AverageScore = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.",
                            Name = "csharp",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 5,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "javascript",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 6,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 7,
                            AverageScore = 0,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 8,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 9,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 10,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 11,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 12,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 2
                        },
                        new
                        {
                            SkillId = 13,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 3
                        },
                        new
                        {
                            SkillId = 14,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 3
                        },
                        new
                        {
                            SkillId = 15,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 4
                        },
                        new
                        {
                            SkillId = 16,
                            AverageScore = 2,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 17,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 18,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 19,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 20,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 21,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 5
                        },
                        new
                        {
                            SkillId = 22,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 6
                        },
                        new
                        {
                            SkillId = 23,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 7
                        },
                        new
                        {
                            SkillId = 24,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 7
                        },
                        new
                        {
                            SkillId = 25,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 26,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 27,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 28,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 29,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 8
                        },
                        new
                        {
                            SkillId = 30,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 31,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 32,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 9
                        },
                        new
                        {
                            SkillId = 33,
                            AverageScore = 3,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 10
                        },
                        new
                        {
                            SkillId = 34,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 10
                        },
                        new
                        {
                            SkillId = 35,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 10
                        },
                        new
                        {
                            SkillId = 36,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 10
                        },
                        new
                        {
                            SkillId = 37,
                            AverageScore = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.",
                            Name = "csharp",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 38,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "javascript",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 39,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 40,
                            AverageScore = 0,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 41,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 42,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 43,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 44,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 45,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 11
                        },
                        new
                        {
                            SkillId = 46,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 47,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 48,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 12
                        },
                        new
                        {
                            SkillId = 49,
                            AverageScore = 1,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 50,
                            AverageScore = 4,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 51,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 52,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 53,
                            AverageScore = 3,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 54,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 55,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 13
                        },
                        new
                        {
                            SkillId = 56,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 14
                        },
                        new
                        {
                            SkillId = 57,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 15
                        },
                        new
                        {
                            SkillId = 58,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 59,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 60,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 61,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 16
                        },
                        new
                        {
                            SkillId = 62,
                            AverageScore = 4,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 17
                        },
                        new
                        {
                            SkillId = 63,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 18
                        },
                        new
                        {
                            SkillId = 64,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 18
                        },
                        new
                        {
                            SkillId = 65,
                            AverageScore = 0,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 19
                        },
                        new
                        {
                            SkillId = 66,
                            AverageScore = 2,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 67,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 68,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 20
                        },
                        new
                        {
                            SkillId = 69,
                            AverageScore = 2,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 21
                        },
                        new
                        {
                            SkillId = 70,
                            AverageScore = 0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.",
                            Name = "csharp",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 71,
                            AverageScore = 4,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "javascript",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 72,
                            AverageScore = 2,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 73,
                            AverageScore = 4,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 74,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "python",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 75,
                            AverageScore = 2,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 22
                        },
                        new
                        {
                            SkillId = 76,
                            AverageScore = 3,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "cpp",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 77,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "php",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 78,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 23
                        },
                        new
                        {
                            SkillId = 79,
                            AverageScore = 4,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 24
                        },
                        new
                        {
                            SkillId = 80,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 24
                        },
                        new
                        {
                            SkillId = 81,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "swift",
                            ProfileId = 25
                        },
                        new
                        {
                            SkillId = 82,
                            AverageScore = 1,
                            Description = "Excepteur sint occaecat cupidatat non proident, sunt in culpa anim id est laborum.",
                            Name = "ruby",
                            ProfileId = 25
                        },
                        new
                        {
                            SkillId = 83,
                            AverageScore = 3,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 26
                        },
                        new
                        {
                            SkillId = 84,
                            AverageScore = 4,
                            Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam.",
                            Name = "java",
                            ProfileId = 26
                        },
                        new
                        {
                            SkillId = 85,
                            AverageScore = 0,
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            Name = "javascript",
                            ProfileId = 27
                        },
                        new
                        {
                            SkillId = 86,
                            AverageScore = 0,
                            Description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            Name = "angular",
                            ProfileId = 27
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Assessment", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.Skill", "Skill")
                        .WithMany("Assessments")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.GeekProfile", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("GeeksDirectory.Data.Entities.Skill", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.GeekProfile", "Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GeeksDirectory.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
